app:
  name: "web_app"
  mod: "dev"
  port: 8081

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "jsy123..."
  dbname: "bluebell"
  max_open_conns: 20
  max_idle_conns: 20

start_time: "2024-03-11"
machine_id: "1"